-- Short interactive musical examples (1–5 measures) embedded in Learn articles.
-- Distinct from `scores`: no PDF/.mscz, looked up by stable `slug`, not browsed as a library.
CREATE TABLE snippets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(255) NOT NULL UNIQUE,
    caption       VARCHAR(500) NOT NULL,
    musicxml_path TEXT,
    concept_tags  TEXT[]       NOT NULL DEFAULT '{}',
    published     BOOLEAN      NOT NULL DEFAULT false,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_snippets_concept_tags ON snippets USING GIN (concept_tags);
CREATE INDEX idx_snippets_published    ON snippets (published);
