-- Per-score attachments: uploaded MP3 recordings and external links (YouTube, etc.),
-- plus admin-authored notes on each. All optional, multiple per score, publicly visible
-- to the same audience as the parent score (anonymous = published-only).
--
-- ON DELETE CASCADE everywhere: deleting a score removes its attachments;
-- deleting an attachment removes its notes. Files in object storage are cleaned
-- up by the service layer (DB CASCADE only handles rows).

CREATE TABLE score_recordings (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_id          BIGINT       NOT NULL REFERENCES scores(id) ON DELETE CASCADE,
    path              TEXT         NOT NULL,
    label             TEXT,
    original_filename TEXT,
    sort_order        INT          NOT NULL DEFAULT 0,
    uploaded_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_score_recordings_score ON score_recordings(score_id);

CREATE TABLE score_references (
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_id   BIGINT  NOT NULL REFERENCES scores(id) ON DELETE CASCADE,
    url        TEXT    NOT NULL,
    label      TEXT,
    kind       TEXT,
    sort_order INT     NOT NULL DEFAULT 0
);
CREATE INDEX idx_score_references_score ON score_references(score_id);

CREATE TABLE score_recording_notes (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT       NOT NULL REFERENCES score_recordings(id) ON DELETE CASCADE,
    body         TEXT         NOT NULL,
    sort_order   INT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_score_recording_notes_recording ON score_recording_notes(recording_id);

CREATE TABLE score_reference_notes (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_id BIGINT       NOT NULL REFERENCES score_references(id) ON DELETE CASCADE,
    body         TEXT         NOT NULL,
    sort_order   INT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_score_reference_notes_reference ON score_reference_notes(reference_id);
